# Generated by Django 6.0.1 on 2026-03-20 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('categoria', models.CharField(choices=[('camara_ip', 'Cámara IP'), ('camara_analogica', 'Cámara Analógica'), ('nvr_dvr', 'NVR / DVR'), ('alarma', 'Sistema de Alarma'), ('sensor', 'Sensor'), ('cable', 'Cable'), ('fuente', 'Fuente de Alimentación'), ('pantalla', 'Pantalla / Display'), ('computadora', 'Equipo Computacional'), ('red', 'Equipo de Red'), ('accesorio', 'Accesorio')], max_length=30, verbose_name='Categoría')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Bs.)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo de alerta')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'projects_insumo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rubro', models.CharField(max_length=100, verbose_name='Rubro')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('correo', models.EmailField(blank=True, max_length=100, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'projects_proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Realizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Bs.)')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Total (Bs.)')),
                ('fecha', models.DateField(verbose_name='Fecha de Compra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'projects_realizar',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Requiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Bs.)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Insumo del Proyecto',
                'verbose_name_plural': 'Insumos del Proyecto',
                'db_table': 'projects_requiere',
                'ordering': ['-created'],
            },
        ),
    ]
