# Generated by Django 6.0.1 on 2026-04-07 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo')),
                ('categoria', models.CharField(choices=[('camara_ip', 'Cámara IP'), ('camara_analogica', 'Cámara Analógica'), ('nvr_dvr', 'NVR / DVR'), ('alarma_sonora', 'Alarma Sonora'), ('alarma_gsm', 'Alarma GSM (activable por llamada)'), ('perifoneo', 'Sistema de Perifoneo'), ('sensor', 'Sensor'), ('cable', 'Cable'), ('fuente', 'Fuente de Alimentación'), ('bateria', 'Batería'), ('pantalla', 'Pantalla / Display'), ('red', 'Equipo de Red'), ('instalacion', 'Material de Instalación')], max_length=30, verbose_name='Categoría')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('rollo', 'Rollo'), ('caja', 'Caja'), ('par', 'Par')], default='unidad', max_length=10, verbose_name='Unidad de medida')),
                ('ultimo_precio_compra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Último Precio Compra (Bs.)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Stock mínimo de alerta')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'inventario_insumo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Razón Social / Nombre de la Empresa')),
                ('rubro', models.CharField(choices=[('camaras_seguridad', 'Cámaras y Equipos de Seguridad'), ('cables_conectores', 'Cables y Conectores'), ('equipos_red', 'Equipos de Red'), ('alarmas_perifoneo', 'Alarmas, Perifoneo y GSM'), ('sensores', 'Sensores'), ('computo', 'Equipos de Cómputo'), ('distribuidor', 'Distribuidor General'), ('otro', 'Otro')], max_length=30, verbose_name='Rubro')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de la Empresa')),
                ('correo', models.EmailField(blank=True, max_length=100, verbose_name='Correo de la Empresa')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('encargado_nombre', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del Encargado')),
                ('encargado_cargo', models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo del Encargado')),
                ('encargado_celular', models.CharField(blank=True, default='', max_length=15, verbose_name='Celular del Encargado')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'inventario_proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Bs.)')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Total (Bs.)')),
                ('fecha', models.DateField(verbose_name='Fecha de Compra')),
                ('numero_factura', models.CharField(blank=True, default='', max_length=100, verbose_name='N° Factura / Comprobante')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='inventario.insumo', verbose_name='Insumo')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='inventario.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'inventario_compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Requiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='inventario.insumo', verbose_name='Insumo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='projects.proyecto', verbose_name='Proyecto')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='projects.sede', verbose_name='Sede de instalación')),
            ],
            options={
                'verbose_name': 'Insumo del Proyecto',
                'verbose_name_plural': 'Insumos del Proyecto',
                'db_table': 'inventario_requiere',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RequiereLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad consumida')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario del lote')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_asignados', to='inventario.compra', verbose_name='Lote de compra')),
                ('requiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.requiere', verbose_name='Requiere')),
            ],
            options={
                'verbose_name': 'Lote FIFO',
                'verbose_name_plural': 'Lotes FIFO',
                'db_table': 'inventario_requiere_lote',
            },
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nombre', 'marca', 'modelo'), name='unique_insumo_nombre_marca_modelo'),
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='insumo_stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('nit', ''), _negated=True), fields=('nit',), name='unique_proveedor_nit_when_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='requiere',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('sede__isnull', True)), fields=('proyecto', 'insumo'), name='unique_requiere_proyecto_insumo_sin_sede'),
        ),
        migrations.AddConstraint(
            model_name='requiere',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('sede__isnull', False)), fields=('proyecto', 'insumo', 'sede'), name='unique_requiere_proyecto_insumo_sede'),
        ),
    ]
