# Generated by Django 6.0.1 on 2026-04-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='requierelote',
            name='costo_unitario',
        ),
    ]
