# Generated by Django 6.0.1 on 2026-04-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('rollo', 'Rollo'), ('caja', 'Caja'), ('par', 'Par')], default='unidad', max_length=10, verbose_name='Unidad de medida'),
        ),
    ]
