# Generated by Django 6.0.1 on 2026-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_empleado_usa_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Costo Unitario (Bs.)'),
        ),
    ]
