# Generated by Django 6.0.1 on 2026-04-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_add_unidad_medida_to_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('camara_ip', 'Cámara IP'), ('camara_analogica', 'Cámara Analógica'), ('nvr_dvr', 'NVR / DVR'), ('alarma_sonora', 'Alarma Sonora'), ('alarma_gsm', 'Alarma GSM (activable por llamada)'), ('perifoneo', 'Sistema de Perifoneo'), ('sensor', 'Sensor'), ('cable', 'Cable'), ('fuente', 'Fuente de Alimentación'), ('bateria', 'Batería'), ('pantalla', 'Pantalla / Display'), ('red', 'Equipo de Red'), ('instalacion', 'Material de Instalación')], max_length=30, verbose_name='Categoría'),
        ),
    ]
