# Generated by Django 6.0.1 on 2026-04-08 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_costo_total_compra_costo_unitario_requirelote'),
        ('projects', '0003_remove_progreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requiere',
            name='unique_requiere_proyecto_insumo_sin_sede',
        ),
        migrations.RemoveConstraint(
            model_name='requiere',
            name='unique_requiere_proyecto_insumo_sede',
        ),
        migrations.AddConstraint(
            model_name='requiere',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('proyecto', 'insumo'), name='unique_requiere_proyecto_insumo_activo'),
        ),
        migrations.AddConstraint(
            model_name='requierelote',
            constraint=models.UniqueConstraint(fields=('requiere', 'compra'), name='unique_requiere_lote_requiere_compra'),
        ),
        migrations.RemoveField(
            model_name='requiere',
            name='sede',
        ),
    ]
