# Generated by Django 6.0.1 on 2026-03-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_insumo_costo_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock mínimo de alerta'),
        ),
    ]
