# Generated by Django 6.0.1 on 2026-04-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_requirelote_auditmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requierelote',
            options={'default_manager_name': 'objects', 'verbose_name': 'Lote FIFO', 'verbose_name_plural': 'Lotes FIFO'},
        ),
    ]
