# Generated by Django 6.0.1 on 2026-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_stock_minimo_default_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo'),
        ),
    ]
