# Generated by Django 6.0.1 on 2026-04-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_add_subtareas_y_subitems_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiere',
            name='durante_garantia',
            field=models.BooleanField(default=False, verbose_name='Agregado durante período de garantía'),
        ),
    ]
