# Generated by Django 6.0.1 on 2026-05-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_requiere_durante_garantia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requierelote',
            name='unique_requirelote_requiere_compra_activo',
        ),
        migrations.DeleteModel(
            name='RequiereLote',
        ),
    ]
