# Generated by Django 6.0.1 on 2026-03-23 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_fix_quality_improvements'),
        ('projects', '0007_fix_quality_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Bs.)')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Total (Bs.)')),
                ('fecha', models.DateField(verbose_name='Fecha de Compra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'inventario_compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='realizar',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='realizar',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='realizar',
            name='proveedor',
        ),
        migrations.AlterUniqueTogether(
            name='requiere',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='requiere',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='inventario.insumo', verbose_name='Insumo'),
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nombre', 'marca', 'modelo'), name='unique_insumo_nombre_marca_modelo'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('nit', ''), _negated=True), fields=('nit',), name='unique_proveedor_nit_when_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='requiere',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('proyecto', 'insumo'), name='unique_requiere_proyecto_insumo_activo'),
        ),
        migrations.AlterModelTable(
            name='insumo',
            table='inventario_insumo',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='inventario_proveedor',
        ),
        migrations.AlterModelTable(
            name='requiere',
            table='inventario_requiere',
        ),
        migrations.AddField(
            model_name='compra',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='compra',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='inventario.insumo', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.DeleteModel(
            name='Realizar',
        ),
    ]
