# Generated by Django 6.0.1 on 2026-05-04 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_reduce_schema_18_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiereLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad de este lote')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.compra', verbose_name='Lote de compra')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('requiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.requiere', verbose_name='Insumo del proyecto')),
            ],
            options={
                'verbose_name': 'Lote FIFO',
                'verbose_name_plural': 'Lotes FIFO',
                'db_table': 'inventario_requirelote',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('requiere', 'compra'), name='unique_requirelote_requiere_compra_activo')],
            },
        ),
    ]
