# Generated by Django 6.0.1 on 2026-03-23 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_inventario_rename_tables_and_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('camara_ip', 'Cámara IP'), ('camara_analogica', 'Cámara Analógica'), ('nvr_dvr', 'NVR / DVR'), ('alarma_sonora', 'Alarma Sonora'), ('alarma_gsm', 'Alarma GSM (activable por llamada)'), ('perifoneo', 'Sistema de Perifoneo'), ('sensor', 'Sensor'), ('cable', 'Cable'), ('fuente', 'Fuente de Alimentación'), ('pantalla', 'Pantalla / Display'), ('computadora', 'Equipo Computacional'), ('red', 'Equipo de Red'), ('accesorio', 'Accesorio')], max_length=30, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(choices=[('camaras_seguridad', 'Cámaras y Equipos de Seguridad'), ('cables_conectores', 'Cables y Conectores'), ('equipos_red', 'Equipos de Red'), ('alarmas_perifoneo', 'Alarmas, Perifoneo y GSM'), ('sensores', 'Sensores'), ('computo', 'Equipos de Cómputo'), ('distribuidor', 'Distribuidor General'), ('otro', 'Otro')], max_length=30, verbose_name='Rubro'),
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='insumo_stock_no_negativo'),
        ),
    ]
