# Generated by Django 6.0.1 on 2026-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_requiere_costo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiere',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total (Bs.)'),
        ),
    ]
