# Generated by Django 6.0.1 on 2026-03-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_equipo_proyecto_m2m'),
        ('projects', '0018_sede_foto_tarea_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requiere',
            name='unique_requiere_proyecto_insumo_activo',
        ),
        migrations.AddField(
            model_name='requiere',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='projects.sede', verbose_name='Sede de instalación'),
        ),
        migrations.AddConstraint(
            model_name='requiere',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('sede__isnull', True)), fields=('proyecto', 'insumo'), name='unique_requiere_proyecto_insumo_sin_sede'),
        ),
        migrations.AddConstraint(
            model_name='requiere',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('sede__isnull', False)), fields=('proyecto', 'insumo', 'sede'), name='unique_requiere_proyecto_insumo_sede'),
        ),
    ]
