# Generated by Django 6.0.1 on 2026-02-21 01:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('nit_ci', models.CharField(max_length=20, verbose_name='NIT/CI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('telefono', models.CharField(max_length=15, verbose_name='Número de Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('tipo_contratante', models.CharField(choices=[('empresa', 'Empresa'), ('personal', 'Personal'), ('entidad_publica', 'Entidad Pública')], default='entidad_publica', max_length=20, verbose_name='Tipo Contratante')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='EntidadPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('representante_legal', models.CharField(max_length=200, verbose_name='Representante Legal')),
                ('contacto', models.CharField(max_length=100, verbose_name='Contacto')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('nombre_entidad', models.CharField(max_length=200, verbose_name='Nombre Entidad')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Entidad Pública',
                'verbose_name_plural': 'Entidades Públicas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('numero_celular', models.CharField(blank=True, max_length=15, verbose_name='Numero Celular')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha Contratación')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('cargo', models.CharField(choices=[('gerente_general', 'Gerente General'), ('tecnico', 'Técnico'), ('analista', 'Analista'), ('desarrollador', 'Desarrollador')], default='gerente_general', max_length=50, verbose_name='Cargo')),
                ('carnet_identidad', models.CharField(max_length=20, unique=True, verbose_name='Carnet de Identidad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_presentacion', models.DateField(verbose_name='Fecha de Presentación')),
                ('monto_presupuesto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Presupuestado')),
                ('requisitos', models.TextField(verbose_name='Requisitos')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('entidad_publica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='projects.entidadpublica', verbose_name='Entidad Pública')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Proyecto')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre Proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio Proyecto')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Final Proyecto')),
                ('estado_proyecto', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estado Proyecto')),
                ('tipo_proyecto', models.CharField(choices=[('licitacion', 'Licitación'), ('contratacion_directa', 'Contratación Directa')], default='contratacion_directa', max_length=30, verbose_name='Tipo Proyecto')),
                ('foto_contrato_firmado', models.ImageField(blank=True, null=True, upload_to='contrato_firmado', verbose_name='Contrato Firmado')),
                ('estado_pago', models.CharField(choices=[('no_pagado', 'No Pagado'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado Completo')], default='no_pagado', max_length=20, verbose_name='Estado de Pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total del Proyecto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.cliente', verbose_name='Contratista')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.empleado', verbose_name='Empleado Asignado')),
                ('propuesta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propuesta', verbose_name='Propuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects_project',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha Pago')),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pagado', max_length=10, verbose_name='Estado Pago')),
                ('tipo_pago', models.CharField(choices=[('parcial', 'Parcial'), ('completo', 'Completo')], default='parcial', max_length=10, verbose_name='Tipo Pago')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Anterior')),
                ('monto_actual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Actual')),
                ('motivo_cambio', models.TextField(verbose_name='Motivo del Cambio')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Historial Pago',
                'verbose_name_plural': 'Historiales de Pagos',
            },
        ),
    ]
