# Generated by Django 5.1.2 on 2026-01-29 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('position', models.CharField(max_length=50, verbose_name='Cargo')),
                ('nit_ci', models.CharField(max_length=20, verbose_name='NIT/CI')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paternal_last_name', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('maternal_last_name', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Número de Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('accountant_type', models.CharField(choices=[('company', 'Empresa'), ('personal', 'Personal'), ('public_entity', 'Entidad Pública')], default='public_entity', max_length=20, verbose_name='Tipo Contratante')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('submission_date', models.DateField(verbose_name='Fecha de presentación')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto presupuesto')),
                ('requirements', models.TextField(verbose_name='Requerimientos')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
            },
        ),
        migrations.CreateModel(
            name='PublicEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('legal_representative', models.CharField(max_length=200, verbose_name='Representante Legal')),
                ('contact', models.CharField(max_length=100, verbose_name='Contacto')),
                ('address', models.CharField(max_length=300, verbose_name='Direccion')),
                ('entity_name', models.CharField(max_length=200, verbose_name='Nombre Entidad')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Public Entity',
                'verbose_name_plural': 'Public Entities',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('numero_celular', models.CharField(blank=True, max_length=15, verbose_name='Numero Celular')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha Contratación')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('cargo', models.CharField(choices=[('gerente_general', 'Gerente General'), ('tecnico', 'Técnico'), ('analista', 'Analista'), ('desarrollador', 'Desarrollador')], default='gerente_general', max_length=50, verbose_name='Cargo')),
                ('carnet_identidad', models.CharField(max_length=20, unique=True, verbose_name='Carnet de Identidad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Proyecto Codigo')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Proyecto Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Proyecto Descripcion')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio Proyecto')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Final Proyecto')),
                ('project_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Proyecto Estado')),
                ('project_type', models.CharField(choices=[('licitacion', 'Licitación'), ('contratacion_directa', 'Contratación Directa')], default='contratacion_directa', max_length=30, verbose_name='Proyecto Tipo')),
                ('photo_signed_contract', models.ImageField(blank=True, null=True, upload_to='contrato_firmado', verbose_name='Contrato Firmado')),
                ('payment_status', models.CharField(choices=[('no_pagado', 'No Pagado'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado Completo')], default='no_pagado', max_length=20, verbose_name='Estado de Pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total del Proyecto')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.empleado', verbose_name='Empleado Asignado')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.cliente', verbose_name='Contratista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.proposal', verbose_name='Propuesta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Previous Amount')),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Amount')),
                ('change_reason', models.TextField(verbose_name='Change Reason')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha Pago')),
                ('status', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pagado', max_length=10, verbose_name='Estado Pago')),
                ('payment_type', models.CharField(choices=[('parcial', 'Parcial'), ('completo', 'Completo')], default='parcial', max_length=10, verbose_name='Tipo Pago')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='public_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.publicentity', verbose_name='Entidad pública'),
        ),
    ]
