# Generated by Django 6.0.1 on 2026-03-20 13:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('numero_celular', models.CharField(blank=True, max_length=15, verbose_name='Numero Celular')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha Contratación')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('cargo', models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('instalador', 'Instalador'), ('tecnico_soporte', 'Técnico de Soporte'), ('secretaria', 'Secretaria')], default='administrador', max_length=50, verbose_name='Cargo')),
                ('carnet_identidad', models.CharField(max_length=20, unique=True, verbose_name='Carnet de Identidad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('nit_ci', models.CharField(blank=True, default='', max_length=20, verbose_name='NIT/CI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=50, verbose_name='Apellido Materno')),
                ('telefono', models.CharField(max_length=15, verbose_name='Número de Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('tipo_contratante', models.CharField(choices=[('empresa', 'Empresa'), ('personal', 'Personal'), ('entidad_publica', 'Entidad Pública')], default='entidad_publica', max_length=20, verbose_name='Tipo Contratante')),
                ('nombre_entidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Entidad')),
                ('representante_legal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Representante Legal')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Proyecto')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre Proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Proyecto')),
                ('estado_proyecto', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estado Proyecto')),
                ('tipo_proyecto', models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('ampliacion', 'Ampliación'), ('mantenimiento', 'Mantenimiento'), ('emergencia', 'Emergencia')], default='instalacion_nueva', max_length=30, verbose_name='Tipo Proyecto')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('estado_pago', models.CharField(choices=[('no_pagado', 'No Pagado'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado Completo')], default='no_pagado', max_length=20, verbose_name='Estado de Pago')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total del Proyecto')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.cliente', verbose_name='Contratista')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects_project',
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('porcentaje', models.PositiveIntegerField(verbose_name='Porcentaje (%)')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
                'ordering': ['-fecha', '-created'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Anterior')),
                ('monto_actual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Actual')),
                ('motivo_cambio', models.TextField(verbose_name='Motivo del Cambio')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Historial Pago',
                'verbose_name_plural': 'Historiales de Pagos',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('empleado', 'Contrato con Empleado'), ('proyecto', 'Contrato con Cliente')], max_length=10, verbose_name='Tipo de Contrato')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de Firma')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto_acordado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Acordado (Bs.)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Documento')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created'],
            },
        ),
    ]
