# Generated by Django 6.0.1 on 2026-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_empleado_usa_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto Total del Proyecto'),
        ),
    ]
