# Generated by Django 6.0.1 on 2026-04-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareachecklist',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='ritmo_semanal',
        ),
        migrations.DeleteModel(
            name='GrupoTarea',
        ),
    ]
