# Generated by Django 5.1.2 on 2024-11-05 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_place_representation', models.CharField(max_length=50, verbose_name='Entidad/Lugar/Representación')),
                ('position', models.CharField(max_length=50, verbose_name='Cargo')),
                ('nit_ci', models.CharField(max_length=20, verbose_name='NIT/CI')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paternal_last_name', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('maternal_last_name', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Número de Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('accountant_type', models.CharField(choices=[('company', 'Empresa'), ('personal', 'Personal'), ('public_entity', 'Entidad Pública')], default='public_entity', max_length=20, verbose_name='Tipo Contratante')),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
            },
        ),
        migrations.CreateModel(
            name='PublicEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_representative', models.CharField(max_length=200, verbose_name='Representante Legal')),
                ('contact', models.CharField(max_length=100, verbose_name='Contacto')),
                ('address', models.CharField(max_length=300, verbose_name='Direccion')),
                ('entity_name', models.CharField(max_length=200, verbose_name='Nombre Entidad')),
            ],
            options={
                'verbose_name': 'Public Entity',
                'verbose_name_plural': 'Public Entities',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name_father', models.CharField(max_length=100)),
                ('last_name_mother', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position', models.CharField(choices=[('gerente_general', 'Gerente General'), ('tecnico', 'Técnico'), ('analista', 'Analista'), ('desarrollador', 'Desarrollador')], default='gerente_general', max_length=50, verbose_name='Cargo')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Carnet de Identidad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10, verbose_name='Payment Status')),
                ('payment_type', models.CharField(choices=[('parcial', 'Parcial'), ('completo', 'Completo')], default='parcial', max_length=10, verbose_name='Payment Type')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Previous Amount')),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Amount')),
                ('change_reason', models.TextField(verbose_name='Change Reason')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(verbose_name='Submission Date')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget Amount')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
                ('public_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.publicentity', verbose_name='Public Entity')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
            },
        ),
    ]
