# Generated by Django 6.0.1 on 2026-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_monto_total_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_salario',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('diario', 'Diario')], default='mensual', max_length=10, verbose_name='Tipo de Salario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario (Bs.)'),
        ),
    ]
