# Generated by Django 5.1.2 on 2024-11-05 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_contractor_publicentity_employee_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publicentity',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
