# Generated by Django 6.0.1 on 2026-04-01 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_fix_cliente_not_null_monto_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_nit_ci_when_not_empty',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.cliente', verbose_name='Contratista'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), models.Q(('nit_ci', ''), _negated=True)), fields=('nit_ci',), name='unique_nit_ci_activo_when_not_empty'),
        ),
    ]
