# Generated by Django 6.0.1 on 2026-04-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_grupo_tarea_ritmo_semanal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
