# Generated by Django 6.0.1 on 2026-04-08 17:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_progreso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de Firma')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto_acordado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Acordado (Bs.)')),
                ('porcentaje_multa_diaria', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='% Multa Diaria')),
                ('porcentaje_multa_maxima', models.DecimalField(decimal_places=2, default=Decimal('20'), help_text="Tope máximo de multa acumulada como % del monto acordado. Al superarlo el estado pasa a 'crítico'.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='% Multa Máxima (tope)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Documento')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Contrato de Proyecto',
                'verbose_name_plural': 'Contratos de Proyectos',
                'ordering': ['-created'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='contrato_proy_fecha_fin_gte_inicio'), models.CheckConstraint(condition=models.Q(('fecha_firma__lte', models.F('fecha_inicio'))), name='contrato_proy_fecha_firma_lte_inicio'), models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('proyecto',), name='unique_contrato_proyecto_activo'), models.CheckConstraint(condition=models.Q(('monto_acordado__gt', 0)), name='contrato_proy_monto_positivo')],
            },
        ),
    ]
