# Generated by Django 5.1.2 on 2026-03-10 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_empleado_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('porcentaje', models.PositiveIntegerField(verbose_name='Porcentaje (%)')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
                'ordering': ['-fecha', '-created'],
            },
        ),
    ]
