# Generated by Django 6.0.1 on 2026-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tipo_salario_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_contratacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_salario',
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_salario',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('diario', 'Diario')], default='mensual', max_length=10, null=True, verbose_name='Tipo de Pago'),
        ),
    ]
