# Generated by Django 6.0.1 on 2026-04-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_move_contratoproyecto_to_projects_add_validations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemplantilla',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='itemplantilla',
            name='created',
        ),
        migrations.RemoveField(
            model_name='itemplantilla',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='itemplantilla',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='itemplantilla',
            name='updated_at',
        ),
    ]
