# Generated by Django 6.0.1 on 2026-03-23 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_mover_campos_a_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('nit_ci', ''), _negated=True), fields=('nit_ci',), name='unique_nit_ci_when_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'empleado'), _negated=True), ('empleado__isnull', False), _connector='OR'), name='contrato_empleado_required_when_tipo_empleado'),
        ),
    ]
