# Generated by Django 6.0.1 on 2026-04-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_asignacion_diaria_dias_laborales'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='proyecto_origen',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo_proyecto': 'instalacion_nueva'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_garantia', to='projects.proyecto', verbose_name='Proyecto de Origen (Garantía)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('ampliacion', 'Ampliación'), ('mantenimiento_garantia', 'Mantenimiento (Garantía)'), ('mantenimiento_externo', 'Mantenimiento Externo'), ('emergencia', 'Emergencia')], db_index=True, default='instalacion_nueva', max_length=30, verbose_name='Tipo Proyecto'),
        ),
    ]
