# Generated by Django 6.0.1 on 2026-03-23 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_fix_critical_db_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpago',
            name='created',
        ),
        migrations.AddField(
            model_name='historialpago',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='historialpago',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Modificación'),
        ),
    ]
