# Generated by Django 6.0.1 on 2026-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='foto_contrato_firmado',
            field=models.FileField(blank=True, null=True, upload_to='contrato_firmado/', verbose_name='Contrato Firmado'),
        ),
    ]
