# Generated by Django 6.0.1 on 2026-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_itemplatilla_sin_auditmodel_jornada_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado_pago',
            field=models.CharField(choices=[('no_pagado', 'No pagado'), ('parcial', 'Pago parcial'), ('pagado', 'Pago completo')], db_index=True, default='no_pagado', max_length=20, verbose_name='Estado de Pago'),
        ),
    ]
