# Generated by Django 6.0.1 on 2026-04-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_tipo_proyecto_mantenimiento_split_proyecto_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cargo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol_contacto',
            field=models.CharField(blank=True, choices=[('propietario', 'Propietario'), ('representante', 'Representante'), ('gerente', 'Gerente'), ('presidente_zona', 'Presidente de Zona'), ('encargado', 'Encargado')], max_length=50, verbose_name='Rol de Contacto'),
        ),
        migrations.AlterField(
            model_name='itemplantilla',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Orden'),
        ),
    ]
