# Generated by Django 6.0.1 on 2026-04-05 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_cargo_to_rol_contacto_en_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento / Multa aplicada (Bs.)'),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_descuento',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Motivo del descuento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rol_contacto',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('representante', 'Representante'), ('gerente', 'Gerente'), ('presidente_zona', 'Presidente de Zona'), ('encargado', 'Encargado')], default='propietario', max_length=50, verbose_name='Rol de Contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_contratante',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('personal', 'Personal'), ('entidad_publica', 'Entidad Pública')], default='personal', max_length=20, verbose_name='Tipo Contratante'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto recibido (Bs.)'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Referencia del lugar'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0)), name='pago_descuento_no_negativo'),
        ),
    ]
