# Generated by Django 6.0.1 on 2026-03-11 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_proyecto_foto_contrato_firmado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proyectos',
            field=models.ManyToManyField(related_name='contratos', to='projects.proyecto', verbose_name='Proyectos'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato', to='projects.empleado', verbose_name='Empleado'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='proyecto',
        ),
    ]
