# Generated by Django 6.0.1 on 2026-03-23 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_fix_important_design_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='porcentaje',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje (%)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado_pago',
            field=models.CharField(choices=[('no_pagado', 'No Pagado'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado Completo')], db_index=True, default='no_pagado', max_length=20, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado_proyecto',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Total del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('ampliacion', 'Ampliación'), ('mantenimiento', 'Mantenimiento'), ('emergencia', 'Emergencia')], db_index=True, default='instalacion_nueva', max_length=30, verbose_name='Tipo Proyecto'),
        ),
    ]
