# Generated by Django 6.0.1 on 2026-04-10 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_registrado_por_to_jornada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tareachecklist',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='tareas_participadas', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
