# Generated by Django 6.0.1 on 2026-04-06 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_descuento_motivo_to_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ritmo_semanal',
            field=models.PositiveSmallIntegerField(default=4, help_text='Promedio de unidades de instalación completadas por semana (ej: 4 cámaras/semana).', verbose_name='Ritmo esperado (grupos/semana)'),
        ),
        migrations.CreateModel(
            name='GrupoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('camara_ip', 'Cámara IP'), ('camara_analogica', 'Cámara Analógica'), ('dvr_nvr', 'DVR / NVR'), ('alarma', 'Sistema de Alarma'), ('sensor', 'Sensor'), ('fibra', 'Fibra Óptica'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha completado')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='projects.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Grupo de Instalación',
                'verbose_name_plural': 'Grupos de Instalación',
                'ordering': ['orden', 'created'],
            },
        ),
        migrations.AddField(
            model_name='tareachecklist',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='projects.grupotarea', verbose_name='Grupo de instalación'),
        ),
    ]
