# Generated by Django 6.0.1 on 2026-04-11 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_participantes_to_tarea_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='proyecto_origen',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo_proyecto__in': ['instalacion_nueva', 'ampliacion']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_derivados', to='projects.proyecto', verbose_name='Proyecto de Origen'),
        ),
    ]
