# Generated by Django 6.0.1 on 2026-03-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_contrato_unique_together_contrato_proyectos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='projects.empleado', verbose_name='Empleado'),
        ),
    ]
