# Generated by Django 5.1.2 on 2024-11-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_payment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Monto Total del Proyecto'),
            preserve_default=False,
        ),
    ]
