# Generated by Django 6.0.1 on 2026-03-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_contrato_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='foto_contrato_firmado',
        ),
    ]
