# Generated by Django 6.0.1 on 2026-04-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_proyecto_origen_admite_ampliacion_y_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoproyecto',
            name='garantia_meses',
            field=models.PositiveSmallIntegerField(default=0, help_text='Meses de garantía incluidos en este contrato (0 = sin garantía).', verbose_name='Meses de Garantía'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('ampliacion', 'Ampliación'), ('mantenimiento_externo', 'Mantenimiento Externo'), ('emergencia', 'Emergencia')], db_index=True, default='instalacion_nueva', max_length=30, verbose_name='Tipo Proyecto'),
        ),
    ]
