# Generated by Django 6.0.1 on 2026-03-26 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_refactor_pagos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialpresupuesto',
            options={'verbose_name': 'Historial Presupuesto', 'verbose_name_plural': 'Historiales de Presupuesto'},
        ),
        migrations.AddField(
            model_name='progreso',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='historialpresupuesto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_presupuesto', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
    ]
