# Generated by Django 6.0.1 on 2026-04-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_eliminar_mantenimiento_garantia_agregar_garantia_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='proyecto_origen',
        ),
    ]
