# Generated by Django 5.1.2 on 2024-12-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_contractor_is_active_proposal_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('no_pagado', 'No Pagado'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado Completo')], default='no_pagado', max_length=20, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Contratación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name_father',
            field=models.CharField(max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name_mother',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Numero Celular'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('parcial', 'Parcial'), ('completo', 'Completo')], default='parcial', max_length=10, verbose_name='Tipo Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10, verbose_name='Estado Pago'),
        ),
    ]
