# Generated by Django 6.0.1 on 2026-03-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_proyecto_foto_contrato_firmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='empleado_asignado',
        ),
    ]
