# Generated by Django 5.1.2 on 2024-12-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_payment_status_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pagado', max_length=10, verbose_name='Estado Pago'),
        ),
    ]
