# Generated by Django 6.0.1 on 2026-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_progreso_auditmodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='contrato_fecha_fin_gte_inicio'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_firma__lte', models.F('fecha_inicio'))), name='contrato_fecha_firma_lte_inicio'),
        ),
    ]
