# Generated by Django 6.0.1 on 2026-03-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_proyecto_empleado_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_inicio',
        ),
    ]
