# Generated by Django 6.0.1 on 2026-04-20 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_eliminar_campo_proyecto_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialpresupuesto',
            options={'verbose_name': 'Historial Contrato', 'verbose_name_plural': 'Historiales de Contrato'},
        ),
        migrations.CreateModel(
            name='SubItemPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Subtarea')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='projects.itemplantilla', verbose_name='Tarea padre')),
            ],
            options={
                'verbose_name': 'Sub-ítem de Plantilla',
                'verbose_name_plural': 'Sub-ítems de Plantilla',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SubtareaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Subtarea')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha completado')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='projects.tareachecklist', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Subtarea',
                'verbose_name_plural': 'Subtareas',
                'ordering': ['orden', 'created'],
            },
        ),
    ]
