# Generated by Django 6.0.1 on 2026-03-11 03:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_proyecto_fechas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de Firma')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto_acordado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Acordado (Bs.)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos_empleados/', verbose_name='Documento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='projects.empleado', verbose_name='Empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_empleados', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Contrato de Empleado',
                'verbose_name_plural': 'Contratos de Empleados',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ContratoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de Firma')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto_acordado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Acordado (Bs.)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos_proyecto/', verbose_name='Documento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_proyecto', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Contrato del Proyecto',
                'verbose_name_plural': 'Contratos de Proyectos',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
