# Generated by Django 6.0.1 on 2026-03-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_contrato_date_constraints'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('tipo', 'proyecto')), fields=('proyecto',), name='unique_contrato_proyecto_activo'),
        ),
    ]
