# Generated by Django 6.0.1 on 2026-03-26 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_contrato_unique_proyecto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='porcentaje',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje (%)'),
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='proyecto_fecha_fin_gte_inicio'),
        ),
    ]
