# Generated by Django 6.0.1 on 2026-04-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_historial_estado_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='representante_legal',
        ),
    ]
