# Generated by Django 5.1.2 on 2024-12-12 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_assigned_employee_project_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo_proposed_contract',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.proposal', verbose_name='Propuesta'),
        ),
    ]
