# Generated by Django 6.0.1 on 2026-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_split_contrato_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('instalador', 'Instalador'), ('tecnico_soporte', 'Técnico de Soporte'), ('secretaria', 'Secretaria')], default='administrador', max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('ampliacion', 'Ampliación'), ('mantenimiento', 'Mantenimiento'), ('emergencia', 'Emergencia')], default='instalacion_nueva', max_length=30, verbose_name='Tipo Proyecto'),
        ),
    ]
