# Generated by Django 6.0.1 on 2026-03-27 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_proyecto_fecha_constraint_progreso_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_salario',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual (30 días)'), ('semanal', 'Semanal (7 días)')], default='mensual', max_length=10, null=True, verbose_name='Tipo de Pago'),
        ),
        migrations.CreateModel(
            name='JornadaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('dias', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.0)], verbose_name='Días trabajados')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='projects.contrato', verbose_name='Contrato')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_empleados', to='projects.proyecto', verbose_name='Proyecto trabajado')),
            ],
            options={
                'verbose_name': 'Jornada de Empleado',
                'verbose_name_plural': 'Jornadas de Empleados',
                'ordering': ['-fecha'],
            },
        ),
    ]
