# Generated by Django 6.0.1 on 2026-04-22 16:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_representante_legal_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio de garantía')),
                ('fecha_vencimiento', models.DateField(verbose_name='Vencimiento de garantía')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantia', to='projects.contratoproyecto', verbose_name='Contrato del proyecto')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('fecha_reporte', models.DateField(verbose_name='Fecha del reporte')),
                ('fecha_reparacion', models.DateField(blank=True, null=True, verbose_name='Fecha de reparación')),
                ('costo_reparacion', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costo absorbido por SOBOTEC — no se cobra al cliente.', max_digits=10, verbose_name='Costo de reparación (Bs.)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_reparacion', 'En Reparación'), ('resuelto', 'Resuelto')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='garantias/evidencias/', verbose_name='Evidencia (foto o PDF)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='projects.garantia', verbose_name='Garantía')),
                ('reparado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
            ],
            options={
                'verbose_name': 'Incidencia de Garantía',
                'verbose_name_plural': 'Incidencias de Garantía',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.AddConstraint(
            model_name='garantia',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__gt', models.F('fecha_inicio'))), name='garantia_vencimiento_posterior_inicio'),
        ),
        migrations.AddConstraint(
            model_name='incidenciagarantia',
            constraint=models.CheckConstraint(condition=models.Q(('costo_reparacion__gte', 0)), name='incidencia_garantia_costo_no_negativo'),
        ),
    ]
