# Generated by Django 6.0.1 on 2026-03-11 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_update_tipo_proyecto_and_cargo_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('categoria', models.CharField(choices=[('camara_ip', 'Cámara IP'), ('camara_analogica', 'Cámara Analógica'), ('nvr_dvr', 'NVR / DVR'), ('alarma', 'Sistema de Alarma'), ('sensor', 'Sensor'), ('cable', 'Cable'), ('fuente', 'Fuente de Alimentación'), ('accesorio', 'Accesorio')], max_length=30, verbose_name='Categoría')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Bs.)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rubro', models.CharField(max_length=100, verbose_name='Rubro')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('correo', models.EmailField(blank=True, max_length=100, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Realizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Bs.)')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Total (Bs.)')),
                ('fecha', models.DateField(verbose_name='Fecha de Compra')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='projects.insumo', verbose_name='Insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='projects.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Requiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Bs.)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='projects.insumo', verbose_name='Insumo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Insumo del Proyecto',
                'verbose_name_plural': 'Insumos del Proyecto',
                'ordering': ['-created'],
            },
        ),
    ]
