# Generated by Django 6.0.1 on 2026-03-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_add_insumo_proveedor_requiere_realizar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requiere',
            unique_together={('proyecto', 'insumo')},
        ),
    ]
