# Generated by Django 6.0.1 on 2026-03-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_jornada_empleado_y_periodo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'proyecto'), _negated=True), ('proyecto__isnull', False), _connector='OR'), name='contrato_proyecto_required_when_tipo_proyecto'),
        ),
    ]
