# Generated by Django 6.0.1 on 2026-04-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_add_garantia_incidencia_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoproyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pagado', max_length=10, verbose_name='Estado'),
        ),
    ]
