# Generated by Django 6.0.1 on 2026-04-29 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_add_estado_to_pagoproyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_inicio_plan', models.DateField(blank=True, null=True, verbose_name='Inicio planificado')),
                ('fecha_fin_plan', models.DateField(blank=True, null=True, verbose_name='Fin planificado')),
                ('dias_planificados', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Días planificados')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_proyecto', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Asignación de proyecto',
                'verbose_name_plural': 'Asignaciones de proyecto',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('proyecto', 'empleado'), name='unique_asignacion_activa_por_proyecto_empleado'), models.CheckConstraint(condition=models.Q(('fecha_fin_plan__isnull', True), ('fecha_inicio_plan__isnull', True), ('fecha_fin_plan__gte', models.F('fecha_inicio_plan')), _connector='OR'), name='asignacion_fecha_fin_gte_inicio')],
            },
        ),
    ]
