# Generated by Django 6.0.1 on 2026-03-30 02:46

from django.db import migrations, models
from django.utils import timezone


def deactivar_contratos_duplicados(apps, schema_editor):
    """Para cada empleado con más de un contrato activo, conserva solo el más reciente."""
    Contrato = apps.get_model('projects', 'Contrato')
    from django.db.models import Count

    empleados_con_duplicados = (
        Contrato.objects.filter(tipo='empleado', activo=True)
        .values('empleado')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
        .values_list('empleado', flat=True)
    )

    for empleado_id in empleados_con_duplicados:
        contratos = list(
            Contrato.objects.filter(empleado_id=empleado_id, tipo='empleado', activo=True)
            .order_by('-created')
        )
        # Conservar el primero (más reciente), desactivar el resto
        for contrato in contratos[1:]:
            contrato.activo = False
            contrato.deleted_at = timezone.now()
            contrato.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_contrato_proyecto_nullable'),
    ]

    operations = [
        migrations.RunPython(deactivar_contratos_duplicados, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(
                condition=models.Q(('activo', True), ('tipo', 'empleado')),
                fields=('empleado',),
                name='unique_contrato_empleado_activo',
            ),
        ),
    ]
