# Generated by Django 6.0.1 on 2026-05-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_add_asignacion_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadoproyecto',
            name='estado_anterior',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='historialestadoproyecto',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Nuevo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado_proyecto',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado Proyecto'),
        ),
    ]
