# Generated by Django 6.0.1 on 2026-03-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_add_correo_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='correo',
        ),
    ]
