# Generated by Django 6.0.1 on 2026-03-30 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_unique_contrato_empleado_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(blank=True, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Equipo del Proyecto'),
        ),
    ]
