# Generated by Django 6.0.1 on 2026-05-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_add_asignacion_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estado', 'Cambio de Estado'), ('presupuesto', 'Cambio de Presupuesto')], max_length=15, verbose_name='Tipo de cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, verbose_name='Estado Nuevo')),
                ('monto_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Anterior')),
                ('monto_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Actual')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo / Observación')),
            ],
            options={
                'verbose_name': 'Historial del Proyecto',
                'verbose_name_plural': 'Historial de Proyectos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='asignacionproyecto',
            name='unique_asignacion_activa_por_proyecto_empleado',
        ),
        migrations.RemoveConstraint(
            model_name='asignacionproyecto',
            name='asignacion_fecha_fin_gte_inicio',
        ),
        migrations.RemoveField(
            model_name='fotosede',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='fotosede',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='fotosede',
            name='subida_por',
        ),
        migrations.RemoveField(
            model_name='historialestadoproyecto',
            name='cambiado_por',
        ),
        migrations.RemoveField(
            model_name='historialestadoproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='historialpresupuesto',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='historialpresupuesto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='itemplantilla',
            name='plantilla',
        ),
        migrations.RemoveField(
            model_name='subitemplantilla',
            name='item',
        ),
        migrations.RemoveConstraint(
            model_name='notificacion',
            name='notificacion_sede_requerida_si_tipo_sede',
        ),
        migrations.RemoveField(
            model_name='plantillatarea',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='plantilla',
        ),
        migrations.AddField(
            model_name='historialproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='historialproyecto',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.RemoveField(
            model_name='asignacionproyecto',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='asignacionproyecto',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='asignacionproyecto',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='FotoSede',
        ),
        migrations.DeleteModel(
            name='HistorialEstadoProyecto',
        ),
        migrations.DeleteModel(
            name='HistorialPresupuesto',
        ),
        migrations.DeleteModel(
            name='ItemPlantilla',
        ),
        migrations.DeleteModel(
            name='SubItemPlantilla',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='sede',
        ),
        migrations.DeleteModel(
            name='PlantillaTarea',
        ),
        migrations.DeleteModel(
            name='AsignacionProyecto',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
