# Generated by Django 6.0.1 on 2026-05-10 00:28

from django.db import migrations, models


def reasignar_ampliacion(apps, schema_editor):
    Proyecto = apps.get_model('projects', 'Proyecto')
    Proyecto.objects.filter(tipo_proyecto='ampliacion').update(tipo_proyecto='instalacion_nueva')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_add_cancelado_estado_proyecto'),
    ]

    operations = [
        migrations.RunPython(reasignar_ampliacion, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('mantenimiento_externo', 'Mantenimiento Externo'), ('emergencia', 'Emergencia')], db_index=True, default='instalacion_nueva', max_length=30, verbose_name='Tipo Proyecto'),
        ),
    ]
