# Generated by Django 6.0.1 on 2026-05-03 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_reduce_schema_18_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='acta_inicio',
            field=models.FileField(blank=True, null=True, upload_to='actas/', verbose_name='Acta de Inicio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_alcance',
            field=models.TextField(blank=True, default='', verbose_name='Alcance del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivo_general',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Objetivo General'),
        ),
        migrations.AddField(
            model_name='tareachecklist',
            name='criterio_aceptacion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Criterio de Aceptación'),
        ),
        migrations.CreateModel(
            name='RiesgoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(verbose_name='Descripción del riesgo')),
                ('categoria', models.CharField(choices=[('tecnico', 'Técnico'), ('humano', 'Humano'), ('externo', 'Externo'), ('financiero', 'Financiero')], default='tecnico', max_length=15, verbose_name='Categoría')),
                ('probabilidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Probabilidad')),
                ('impacto', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='medio', max_length=10, verbose_name='Impacto')),
                ('plan_mitigacion', models.TextField(blank=True, default='', verbose_name='Plan de Mitigación')),
                ('estado', models.CharField(choices=[('identificado', 'Identificado'), ('en_seguimiento', 'En Seguimiento'), ('cerrado', 'Cerrado')], db_index=True, default='identificado', max_length=20, verbose_name='Estado')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='projects.proyecto', verbose_name='Proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Riesgo del Proyecto',
                'verbose_name_plural': 'Riesgos del Proyecto',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha_inicio_plan', models.DateField(blank=True, null=True, verbose_name='Inicio Planificado')),
                ('fecha_fin_plan', models.DateField(blank=True, null=True, verbose_name='Fin Planificado')),
                ('dias_planificados', models.PositiveSmallIntegerField(default=0, verbose_name='Días Planificados')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_proyecto', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Asignación al Proyecto',
                'verbose_name_plural': 'Asignaciones al Proyecto',
                'ordering': ['fecha_inicio_plan'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('proyecto', 'empleado'), name='unique_asignacion_proyecto_empleado_activo'), models.CheckConstraint(condition=models.Q(('fecha_fin_plan__isnull', True), ('fecha_inicio_plan__isnull', True), ('fecha_fin_plan__gte', models.F('fecha_inicio_plan')), _connector='OR'), name='asignacion_fecha_fin_gte_inicio')],
            },
        ),
    ]
