# Generated by Django 6.0.1 on 2026-03-30 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_equipo_proyecto_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Referencia')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Indicaciones')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Sede de Instalación',
                'verbose_name_plural': 'Sedes de Instalación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sede_completada', 'Sede completada'), ('tarea_completada', 'Tarea completada'), ('general', 'General')], default='general', max_length=20, verbose_name='Tipo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.proyecto', verbose_name='Proyecto')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('foto', models.ImageField(upload_to='sedes/fotos/', verbose_name='Foto')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('subida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Subida por')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Foto de Sede',
                'verbose_name_plural': 'Fotos de Sede',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TareaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Tarea')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha completado')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='projects.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Tarea Checklist',
                'verbose_name_plural': 'Tareas Checklist',
                'ordering': ['orden', 'created'],
            },
        ),
    ]
