# Generated by Django 6.0.1 on 2026-03-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_add_correo_empleado_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='correo',
        ),
    ]
