# Generated by Django 6.0.1 on 2026-05-10 00:34

from django.db import migrations, models


def reasignar_emergencia(apps, schema_editor):
    Proyecto = apps.get_model('projects', 'Proyecto')
    Proyecto.objects.filter(tipo_proyecto='emergencia').update(tipo_proyecto='mantenimiento_externo')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_eliminar_ampliacion_tipo_proyecto'),
    ]

    operations = [
        migrations.RunPython(reasignar_emergencia, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('mantenimiento_externo', 'Mantenimiento Externo')], db_index=True, default='instalacion_nueva', max_length=30, verbose_name='Tipo Proyecto'),
        ),
    ]
