# Generated by Django 6.0.1 on 2026-03-31 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_pagoempleado_conceptos_reales'),
        ('projects', '0018_sede_foto_tarea_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaempleado',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_cubiertas', to='pagos.pagoempleado', verbose_name='Pago que cubre esta jornada'),
        ),
    ]
