# Generated by Django 6.0.1 on 2026-03-16 15:24

from django.db import migrations, models
from django.db.models import Sum


def inicializar_stock(apps, schema_editor):
    Insumo   = apps.get_model('projects', 'Insumo')
    Realizar = apps.get_model('projects', 'Realizar')
    Requiere = apps.get_model('projects', 'Requiere')
    for insumo in Insumo.objects.all():
        compras   = Realizar.objects.filter(insumo=insumo).aggregate(t=Sum('cantidad'))['t'] or 0
        asignados = Requiere.objects.filter(insumo=insumo).aggregate(t=Sum('cantidad'))['t'] or 0
        insumo.stock = compras - asignados
        insumo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_correo_empleado_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock mínimo de alerta'),
        ),
        migrations.RunPython(inicializar_stock, migrations.RunPython.noop),
    ]
