# Generated by Django 6.0.1 on 2026-03-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_jornada_pago_fk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'sede_completada'), _negated=True), ('sede__isnull', False), _connector='OR'), name='notificacion_sede_requerida_si_tipo_sede'),
        ),
        migrations.AddConstraint(
            model_name='tareachecklist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completado', True), _negated=True), ('completado_por__isnull', False), _connector='OR'), name='tarea_completado_por_requerido_si_completado'),
        ),
    ]
