# Generated by Django 6.0.1 on 2026-05-04 02:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_add_notificacion_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignacionproyecto',
            name='unique_asignacion_proyecto_empleado_activo',
        ),
        migrations.RemoveConstraint(
            model_name='asignacionproyecto',
            name='asignacion_fecha_fin_gte_inicio',
        ),
        migrations.RemoveConstraint(
            model_name='contratoproyecto',
            name='contrato_proy_fecha_fin_gte_inicio',
        ),
        migrations.RemoveConstraint(
            model_name='contratoproyecto',
            name='contrato_proy_fecha_firma_lte_inicio',
        ),
        migrations.RemoveConstraint(
            model_name='contratoproyecto',
            name='unique_contrato_proyecto_activo',
        ),
        migrations.RemoveConstraint(
            model_name='contratoproyecto',
            name='contrato_proy_monto_positivo',
        ),
        migrations.RemoveConstraint(
            model_name='garantia',
            name='garantia_vencimiento_posterior_inicio',
        ),
        migrations.RemoveField(
            model_name='historialproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='historialproyecto',
            name='registrado_por',
        ),
        migrations.RemoveConstraint(
            model_name='incidenciagarantia',
            name='incidencia_garantia_costo_no_negativo',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='riesgoproyecto',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='riesgoproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='riesgoproyecto',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='subtareachecklist',
            name='completado_por',
        ),
        migrations.RemoveField(
            model_name='subtareachecklist',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='subtareachecklist',
            name='tarea',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='documento_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Documento Contrato'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Límite (Contrato)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='garantia_meses',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Meses de Garantía'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='monto_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Acordado (Bs.)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='porcentaje_multa_diaria',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='% Multa Diaria'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='porcentaje_multa_maxima',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='% Multa Máxima (tope)'),
        ),
        migrations.RemoveField(
            model_name='asignacionproyecto',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='asignacionproyecto',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='asignacionproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='contratoproyecto',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='contratoproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='deleted_by',
        ),
        migrations.DeleteModel(
            name='HistorialProyecto',
        ),
        migrations.RemoveField(
            model_name='incidenciagarantia',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='incidenciagarantia',
            name='garantia',
        ),
        migrations.RemoveField(
            model_name='incidenciagarantia',
            name='reparado_por',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='RiesgoProyecto',
        ),
        migrations.DeleteModel(
            name='SubtareaChecklist',
        ),
        migrations.DeleteModel(
            name='AsignacionProyecto',
        ),
        migrations.DeleteModel(
            name='ContratoProyecto',
        ),
        migrations.DeleteModel(
            name='Garantia',
        ),
        migrations.DeleteModel(
            name='IncidenciaGarantia',
        ),
    ]
