# Generated by Django 6.0.1 on 2026-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_normalizar_tipo_contratante_rol_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rol_contacto',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('encargado', 'Encargado'), ('gerente', 'Gerente'), ('representante', 'Representante')], default='propietario', max_length=50, verbose_name='Rol de Contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_contratante',
            field=models.CharField(choices=[('personal', 'Personal / Negocio'), ('entidad_publica', 'Entidad Pública')], default='personal', max_length=20, verbose_name='Tipo Contratante'),
        ),
    ]
