# Generated by Django 6.0.1 on 2026-03-16 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_add_stock_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs.)')),
                ('fecha', models.DateField(verbose_name='Fecha de Pago')),
                ('concepto', models.CharField(help_text='Ej: Anticipo, Saldo final, Mensualidad', max_length=255, verbose_name='Concepto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='projects.contratoempleado', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pago a Empleado',
                'verbose_name_plural': 'Pagos a Empleados',
                'ordering': ['-fecha'],
            },
        ),
    ]
