# Generated by Django 6.0.1 on 2026-05-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_absorb_contract_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_riesgo',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del Riesgo / Plan de Mitigación'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nivel_riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10, verbose_name='Nivel de Riesgo'),
        ),
    ]
