# Generated by Django 6.0.1 on 2026-03-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_add_pago_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='estado',
            field=models.CharField(choices=[('en_evaluacion', 'En Evaluación'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='en_evaluacion', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_estimada_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización'),
        ),
        migrations.AddField(
            model_name='realizar',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('camara_ip', 'Cámara IP'), ('camara_analogica', 'Cámara Analógica'), ('nvr_dvr', 'NVR / DVR'), ('alarma', 'Sistema de Alarma'), ('sensor', 'Sensor'), ('cable', 'Cable'), ('fuente', 'Fuente de Alimentación'), ('pantalla', 'Pantalla / Display'), ('computadora', 'Equipo Computacional'), ('red', 'Equipo de Red'), ('accesorio', 'Accesorio')], max_length=30, verbose_name='Categoría'),
        ),
    ]
