# Generated by Django 6.0.1 on 2026-03-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_agregar_campos_incompletos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='entidadpublica',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación'),
        ),
        migrations.AddField(
            model_name='entidadpublica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='entidadpublica',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
    ]
