# Generated by Django 6.0.1 on 2026-03-17 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auditmodel_herencia_cliente_entidad_propuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='entidad_publica',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_entidad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Entidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='projects.cliente', verbose_name='Cliente / Entidad'),
        ),
        migrations.DeleteModel(
            name='EntidadPublica',
        ),
    ]
