# Generated by Django 6.0.1 on 2026-03-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_eliminar_entidad_publica_consolidar_en_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='propuesta',
        ),
        migrations.DeleteModel(
            name='Propuesta',
        ),
    ]
