# Generated by Django 5.1.2 on 2026-03-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_eliminar_propuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit_ci',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='NIT/CI'),
        ),
    ]
