# Generated by Django 5.1.2 on 2026-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_campos_opcionales_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_estimada_fin',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='observacion',
            field=models.TextField(blank=True, default='', verbose_name='Observación'),
        ),
    ]
