# Generated by Django 6.0.1 on 2026-03-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_empleado_usa_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='pagoempleado',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='pagoempleado',
            name='concepto',
            field=models.CharField(choices=[('anticipo', 'Anticipo'), ('mensualidad', 'Mensualidad'), ('saldo_final', 'Saldo Final'), ('otro', 'Otro')], max_length=20, verbose_name='Concepto'),
        ),
    ]
