# Generated by Django 6.0.1 on 2026-03-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_pagoempleado_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(db_index=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs.)'),
        ),
    ]
