# Generated by Django 6.0.1 on 2026-03-29 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_pagobase_abstract'),
        ('projects', '0015_contrato_proyecto_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pagoempleado',
            name='unique_pago_empleado_saldo_final_activo',
        ),
        migrations.AlterField(
            model_name='pagoempleado',
            name='concepto',
            field=models.CharField(choices=[('pago_jornada', 'Pago por jornada(s)'), ('adelanto', 'Adelanto'), ('liquidacion', 'Liquidación final'), ('dia_extra', 'Día extra fuera del contrato'), ('otro', 'Otro')], max_length=20, verbose_name='Concepto'),
        ),
        migrations.AddConstraint(
            model_name='pagoempleado',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('concepto', 'liquidacion')), fields=('contrato',), name='unique_pago_empleado_liquidacion_activo'),
        ),
    ]
