# Generated by Django 6.0.1 on 2026-04-07 15:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='empleados.contratoempleado', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_empleados', to='projects.proyecto', verbose_name='Proyecto trabajado'),
        ),
        migrations.AddField(
            model_name='pagoempleado',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='empleados.contratoempleado', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='pagoempleado',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_cubiertas', to='empleados.pagoempleado', verbose_name='Pago que cubre esta jornada'),
        ),
        migrations.AddConstraint(
            model_name='contratoempleado',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='contrato_emp_fecha_fin_gte_inicio'),
        ),
        migrations.AddConstraint(
            model_name='contratoempleado',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_firma__lte', models.F('fecha_inicio'))), name='contrato_emp_fecha_firma_lte_inicio'),
        ),
        migrations.AddConstraint(
            model_name='contratoempleado',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empleado',), name='unique_contrato_empleado_activo'),
        ),
        migrations.AddConstraint(
            model_name='contratoempleado',
            constraint=models.CheckConstraint(condition=models.Q(('monto_acordado__gt', 0)), name='contrato_emp_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='contratoempleado',
            constraint=models.CheckConstraint(condition=models.Q(('dias_laborales__gt', 0)), name='contrato_emp_dias_laborales_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagoempleado',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pagoempleado_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagoempleado',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('concepto', 'liquidacion')), fields=('contrato',), name='unique_pago_empleado_liquidacion_activo'),
        ),
        migrations.AddConstraint(
            model_name='jornadaempleado',
            constraint=models.CheckConstraint(condition=models.Q(('dias', Decimal('0.5')), ('dias', Decimal('1.0')), _connector='OR'), name='jornada_dias_validos'),
        ),
        migrations.AddConstraint(
            model_name='jornadaempleado',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('contrato', 'proyecto', 'fecha'), name='unique_jornada_contrato_proyecto_fecha'),
        ),
    ]
