# Generated by Django 6.0.1 on 2026-04-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContratoProyecto',
        ),
    ]
