# Generated by Django 6.0.1 on 2026-04-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_move_contratoproyecto_to_projects_add_validations'),
        ('projects', '0005_itemplatilla_sin_auditmodel_jornada_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadaempleado',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_empleados', to='projects.proyecto', verbose_name='Proyecto trabajado'),
        ),
    ]
