# Generated by Django 6.0.1 on 2026-04-02 13:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_protect_cliente_fk_unique_nit_activo'),
        ('projects', '0004_asignacion_diaria_dias_laborales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('completo', 'Día completo (1.0)'), ('manana', 'Mañana — Medio día (0.5)'), ('tarde', 'Tarde — Medio día (0.5)')], default='completo', max_length=10, verbose_name='Turno')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Asignación Diaria',
                'verbose_name_plural': 'Asignaciones Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='contratoempleado',
            name='tipo_salario',
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='dias_laborales',
            field=models.PositiveIntegerField(default=28, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días laborales acordados'),
        ),
        migrations.AddConstraint(
            model_name='contratoempleado',
            constraint=models.CheckConstraint(condition=models.Q(('dias_laborales__gt', 0)), name='contrato_emp_dias_laborales_positivo'),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='instalador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_instalador', to=settings.AUTH_USER_MODEL, verbose_name='Instalador'),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_diarias', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='projects.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='tareas_realizadas',
            field=models.ManyToManyField(blank=True, related_name='asignaciones', to='projects.tareachecklist', verbose_name='Tareas realizadas'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas', to='empleados.asignaciondiaria', verbose_name='Asignación de origen'),
        ),
    ]
