# Generated by Django 6.0.1 on 2026-04-10 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_itemplatilla_sin_auditmodel_jornada_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaempleado',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_registradas_por', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
