# Generated by Django 6.0.1 on 2026-04-03 15:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_asignacion_diaria_dias_laborales'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoproyecto',
            name='porcentaje_multa_diaria',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='% Multa Diaria'),
        ),
    ]
