# Generated by Django 6.0.1 on 2026-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_add_registrado_por_to_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('instalador', 'Instalador'), ('tecnico_soporte', 'Técnico'), ('secretaria', 'Secretaria')], default='administrador', max_length=50, verbose_name='Cargo'),
        ),
    ]
