# Generated by Django 6.0.1 on 2026-04-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_add_subtareas_y_subitems_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoempleado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pagado', max_length=10, verbose_name='Estado'),
        ),
    ]
