# Generated by Django 6.0.1 on 2026-04-05 01:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_contrato_proyecto_multa_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoproyecto',
            name='porcentaje_multa_maxima',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), help_text="Tope máximo de multa acumulada como % del monto acordado. Al superarlo el estado pasa a 'crítico'.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='% Multa Máxima (tope)'),
        ),
    ]
