# Generated by Django 6.0.1 on 2026-05-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_add_estado_to_pagoempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoempleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('diario', 'Por día (jornada)'), ('mensual', 'Mensual')], default='diario', max_length=10, verbose_name='Tipo de contrato'),
        ),
    ]
