# Generated by Django 6.0.1 on 2026-04-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_add_porcentaje_multa_maxima_contrato_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornadaempleado',
            name='asignacion',
        ),
        migrations.DeleteModel(
            name='AsignacionDiaria',
        ),
    ]
