# Generated by Django 6.0.1 on 2026-05-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_add_tipo_contrato_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoempleado',
            name='tipo_contrato',
        ),
    ]
