# Generated by Django 6.0.1 on 2026-04-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_remove_asignacion_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaempleado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='jornadaempleado',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de rechazo'),
        ),
    ]
