# Generated by Django 6.0.1 on 2026-05-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_add_modificado_por_to_audit_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoempleado',
            name='tipo_pago',
        ),
    ]
