# Generated by Django 6.0.1 on 2026-06-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_remove_tipo_pago_from_pago_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoempleado',
            name='concepto',
            field=models.CharField(choices=[('pago_jornada', 'Pago por jornada(s)'), ('adelanto', 'Adelanto'), ('liquidacion', 'Liquidación final')], max_length=20, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='pagoempleado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
